apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-service
  namespace: fluzz-banking
  labels:
    app: fraud-detection
    component: api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: fraud-detection
    component: api
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  sessionAffinity: None